### ISSUE TITLE
DT: Shared MDIO, gem{0, 3} (w/ Linux 6.1) 

### ISSUE THREAD

**Issue by peteut** [enclustra/Mercury_XU1_ST1_Reference_Design#2]
When enabling `gem3` on a `me-xu1-15eg` SOM, the second MDIO node (address 7) was not probed (Linux 6.1, Yocto Mickledore):

```
[    3.794919] macb ff0e0000.ethernet eth1: Defer probe as mdio producer axi is not probed
```

According the scheme [cdns,macb.yaml](https://github.com/Xilinx/linux-xlnx/blob/xlnx_rebase_v6.1_LTS/Documentation/devicetree/bindings/net/cdns%2Cmacb.yaml#L124) the PHY settings shall be placed in the `mdio` property. 

Changing the DT accordingly indeed resolved the issue:

```
[    6.150211] macb ff0b0000.ethernet end0: renamed from eth0
[    6.187505] macb ff0e0000.ethernet end1: renamed from eth1
[    6.741615] macb ff0b0000.ethernet end0: PHY [ff0b0000.ethernet-ffffffff:03] driver [Micrel KSZ9031 Gigabit PHY] (irq=POLL)
[    6.752798] macb ff0b0000.ethernet end0: configuring for phy/rgmii-id link mode
[    6.798861] pps pps0: new PPS source ptp0
[    6.821227] macb ff0b0000.ethernet: gem-ptp-timer ptp clock registered.
[    6.900183] macb ff0e0000.ethernet end1: PHY [ff0b0000.ethernet-ffffffff:07] driver [Micrel KSZ9031 Gigabit PHY] (irq=POLL)
[    6.911349] macb ff0e0000.ethernet end1: configuring for phy/rgmii-id link mode
```

**Comment by andreas-buerkler-enclustra** [comment]
Thank you for the information. For the currently supported Linux kernel (5.15) it seems to work as it is, but we might update that in the next update.

**Comment by peteut** [comment]
> Thank you for the information. For the currently supported Linux kernel (5.15) it seems to work as it is, but we might update that in the next update.

Thanks, I was not aware of the DT scheme change! Will update the title accordingly.
